### ISSUE TITLE
Goland cant make breakpoints working 

### ISSUE THREAD

**Issue by hugoalexmartins** [hanrok/godebug#1]
Hey, 
I have  been trying to make this work, standalone with you own code base.
Everything seems be working, hot reload, build etc.
But for some reason that I dont know exactly the beakpoints are not working as expected.
So when I add a breakpoint and make a nc localhost 8080 request, I can write something but after I cant see it placed on my screen ...
Any tip you can send please ?
Thanks in advanced.

**Comment by hanrok** [comment]
Hi, 
Can you please tell me what is your setup? And why are you using nc?

**Comment by hugoalexmartins** [comment]
Hi,
thanks for your reply.
I am using Ubuntu 18.04.3 and Docker 19.03.5.
Is where I am as you can see the screen shot:

![screenshot](https://user-images.githubusercontent.com/3170222/71615688-6066b580-2baa-11ea-9e10-cd85cf90969c.png)

And here it its my GoLand seems not started:

![goland](https://user-images.githubusercontent.com/3170222/71615754-b76c8a80-2baa-11ea-9a90-ad5294bfcc3c.png)

**Comment by hanrok** [comment]
Since I don't see the "Starting up repeater" and the breakpoint doesn't get hit I think it's likely to be  an issue for GoLand to connect to `dlv` server inside the container.
I'll try to investigate it tonight, did you just checkout the repo config GoLand and run it as in the post?

**Comment by hugoalexmartins** [comment]
Yes I checkout your repo.
But well I've added 
go run main.go &

![Screenshot from 2019-12-31 10-00-55](https://user-images.githubusercontent.com/3170222/71617767-7e391800-2bb4-11ea-96a4-651586a1aeb9.png)

to startScript.sh and now I have:

![1](https://user-images.githubusercontent.com/3170222/71617368-a45db880-2bb2-11ea-97c1-b8c06d8cae1b.png)

But cant start debuging it.
Let me know if you figure what I am doing wrong.
Thanks

**Comment by baturorkun** [comment]
it is same. it is not working :(

Running server
API server listening at: [::]:40000
Delve PID: 8, Server PID: 19
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
2020/03/04 14:24:52 Starting up repeater

**Comment by hanrok** [comment]
I'll take a look at that. Will make it work :)

**Comment by hanrok** [comment]
Hi, I just ran it from scratch and it does work for me. I added README.md file to explain the steps I did to run it.
I run it on macOS Catalina? Can you please give me more details about your setup?
